import { CheckCircle2, ChevronRight, Clock3, Download, FileText, History, Search, ShieldCheck } from "lucide-react";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import type { ArchivedIncident, IncidentSeverity } from "@/types/operations";
import { SignalDock } from "./SignalDock";

const severities: Array<IncidentSeverity | "ALL"> = ["ALL", "P1_CRITICAL", "P2_HIGH", "P3_MEDIUM", "P4_LOW"];
export interface ArchiveViewProps { incidents: ArchivedIncident[]; query: string; severity: IncidentSeverity | "ALL"; dateRange: string; selectedIncident: ArchivedIncident | null; replayTab: "waterfall" | "approvals" | "diff" | "rca"; notice: string; onQueryChange: (value: string) => void; onSeverityChange: (value: IncidentSeverity | "ALL") => void; onDateRangeChange: (value: string) => void; onReplay: (incident: ArchivedIncident | null) => void; onReplayTabChange: (tab: "waterfall" | "approvals" | "diff" | "rca") => void; onExport: (incident: ArchivedIncident, format: "JSON" | "RCA") => void; }

export function ArchiveView({ incidents, query, severity, dateRange, selectedIncident, replayTab, notice, onQueryChange, onSeverityChange, onDateRangeChange, onReplay, onReplayTabChange, onExport }: ArchiveViewProps) {
  return <section className="operations-view archive-view" aria-label="Incident Archive view"><header className="ops-topbar"><div><p className="eyebrow">Audit trail</p><h1>Incident archive</h1><p>Recovery evidence, approval context, and action history remain sealed together.</p></div><span className="archive-retention"><ShieldCheck size={15} />Protected retention</span></header>
    <div className="ops-metric-grid archive-metrics"><article><span>Resolved incidents</span><strong>248</strong><small>90-day index</small></article><article className="is-positive"><span>Median MTTR</span><strong>22m</strong><small>Across protected hosts</small></article><article className="is-blue"><span>Agent actions</span><strong>3,841</strong><small>Audit window</small></article><article><span>Approval compliance</span><strong>99.4%</strong><small>Human gate record</small></article></div>
    <section className="ops-panel glass-surface archive-controls"><label className="ops-search"><Search size={15} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search ID, host, root cause, or title" aria-label="Search incident archive" /></label><div className="ops-tabs archive-severity-tabs">{severities.map((item) => <button key={item} type="button" className={severity === item ? "is-active" : ""} onClick={() => onSeverityChange(item)}>{item === "ALL" ? "All severity" : item.replace("_", " ")}</button>)}</div><select className="archive-date-select" value={dateRange} onChange={(event) => onDateRangeChange(event.target.value)} aria-label="Incident date range"><option value="24_HOURS">24 hours</option><option value="7_DAYS">7 days</option><option value="30_DAYS">30 days</option><option value="90_DAYS">90 days</option></select></section><SignalDock eyebrow="Archive phase" title="Recovery surface sealed." detail="Approval records remain intact across the resolved incident ledger and its protected retention window." values={[{ label: "Evidence locks", value: "248" }, { label: "Last seal", value: "08:57" }, { label: "RCA queue", value: "01" }]} />{notice && <p className="operation-notice"><Download size={15} />{notice}</p>}
    <section className="ops-panel glass-surface incident-table"><div className="incident-table-head"><span>Incident</span><span>Severity & status</span><span>Attribution</span><span>Actions</span></div><div>{incidents.map((incident) => <article className="incident-row" key={incident.id} onClick={() => onReplay(incident)} tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter") onReplay(incident); }}><div className="incident-summary"><b>{incident.id}</b><div><strong>{incident.title}</strong><small>{incident.timestamp} · {incident.duration}</small></div></div><div><span className={`incident-severity incident-severity--${incident.severity.toLowerCase()}`}>{incident.severity.replace("_", " ")}</span><small className="incident-status">{incident.status.replaceAll("_", " ")}</small></div><div className="incident-attribution"><strong>{incident.targetHost}</strong><small>{incident.agentVersion} · {incident.totalCommandsExecuted} commands · {incident.approverOperator}</small></div><div className="incident-actions" onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => onExport(incident, "JSON")}><Download size={14} />JSON</button><button type="button" onClick={() => onExport(incident, "RCA")}><FileText size={14} />RCA</button><ChevronRight size={15} /></div></article>)}</div></section>
    <Dialog open={Boolean(selectedIncident)} onOpenChange={(open) => { if (!open) onReplay(null); }}><DialogContent className="luma-management-dialog ops-drawer-dialog incident-replay-dialog" showCloseButton={false}>{selectedIncident && <div className="ops-drawer-shell"><header className="ops-drawer-header"><div><p className="eyebrow">Incident replay · {selectedIncident.id}</p><DialogTitle>{selectedIncident.title}</DialogTitle><DialogDescription>{selectedIncident.targetHost} · {selectedIncident.timestamp} · {selectedIncident.duration}</DialogDescription></div><DialogClose className="management-dialog-close" aria-label="Close incident replay">×</DialogClose></header><div className="replay-tabs" role="tablist">{([ ["waterfall", "Execution waterfall"], ["approvals", "Approval log"], ["diff", "AST & diff"], ["rca", "Post-mortem"] ] as const).map(([id, label]) => <button type="button" key={id} role="tab" aria-selected={replayTab === id} className={replayTab === id ? "is-active" : ""} onClick={() => onReplayTabChange(id)}>{label}</button>)}</div><section className="ops-drawer-body replay-content">{replayTab === "waterfall" && <ol className="execution-timeline replay-waterfall"><li><time>00:00</time><code>Incident trigger received and scope isolated</code><b className="ops-status ops-status--success">CAPTURED</b></li><li><time>00:03</time><code>Read-only diagnostics completed</code><b className="ops-status ops-status--success">SUCCESS</b></li><li><time>00:06</time><code>Policy-gated action submitted</code><b className="ops-status ops-status--reconnecting">GATED</b></li><li><time>{selectedIncident.duration}</time><code>Resolution evidence archived</code><b className="ops-status ops-status--success">CLOSED</b></li></ol>}{replayTab === "approvals" && <div className="approval-log">{selectedIncident.approvalEvents.map((event) => <article key={`${event.time}-${event.note}`}><span className={event.decision === "APPROVED" ? "is-approved" : "is-rejected"}>{event.decision === "APPROVED" ? <CheckCircle2 size={15} /> : <History size={15} />}</span><div><strong>{event.decision} · {event.operator}</strong><p>{event.note}</p></div><time>{event.time}</time></article>)}</div>}{replayTab === "diff" && <div className="diff-preview"><p><span>AST expression</span><code>systemctl stop lupin-relay</code></p><pre><del>- Restart=always</del>{"\n"}<ins>+ Restart=on-failure</ins>{"\n"}<ins>+ RestartSec=5</ins></pre></div>}{replayTab === "rca" && <article className="rca-preview"><Clock3 size={18} /><div><p className="eyebrow">Automated post-mortem</p><h2>Policy gate preserved recovery context.</h2><p>The affected operation was isolated before mutation. Diagnostic data and the final approval record are attached to this archive entry for follow-up.</p></div></article>}</section></div>}</DialogContent></Dialog>
  </section>;
}
