import { AlertTriangle, Braces, ChevronDown, Code2, Plus, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import type { AstSimulation, PolicyRule, SafetyEnforcementMode } from "@/types/operations";
import { SignalDock } from "./SignalDock";

const categoryLabels: Record<PolicyRule["category"], string> = { DESTRUCTIVE_FS: "Destructive file system", PRIVILEGE_ESCALATION: "Privilege escalation", NETWORK_EXFIL: "Network exfiltration", PROCESS_TERMINATION: "Process termination" };

export interface GovernanceViewProps { profile: string; profiles: readonly string[]; mode: SafetyEnforcementMode; rules: PolicyRule[]; stats: { active: number; blacklisted: number; highRisk: number; intercepted: number }; expandedRuleId: string | null; editorOpen: boolean; notice: string; astSimulation: AstSimulation; onProfileChange: (value: string) => void; onModeChange: (mode: SafetyEnforcementMode) => void; onExpandRule: (id: string | null) => void; onToggleRule: (id: string) => void; onOpenEditor: (open: boolean) => void; onSaveRule: () => void; onAnalyze: (command: string) => void; }

export function GovernanceView({ profile, profiles, mode, rules, stats, expandedRuleId, editorOpen, notice, astSimulation, onProfileChange, onModeChange, onExpandRule, onToggleRule, onOpenEditor, onSaveRule, onAnalyze }: GovernanceViewProps) {
  return <section className="operations-view governance-view" aria-label="AST Safety and Policy Governance view">
    <header className="ops-topbar"><div><p className="eyebrow">AST Safety</p><h1>Policy governance</h1><p>Protected syntax stays observable, explained, and gated before mutation.</p></div><button className="ops-primary-button" type="button" onClick={() => onOpenEditor(true)}><Plus size={16} />Define policy rule</button></header>
    <section className="ops-panel glass-surface governance-controls"><label className="ops-select-label">Policy profile<select value={profile} onChange={(event) => onProfileChange(event.target.value)}>{profiles.map((item) => <option key={item}>{item}</option>)}</select></label><div className="segmented-control" aria-label="Safety enforcement mode">{(["AUTONOMOUS", "STRICT_GATED", "DRY_RUN"] as SafetyEnforcementMode[]).map((item) => <button type="button" key={item} className={mode === item ? "is-active" : ""} aria-pressed={mode === item} onClick={() => onModeChange(item)}>{item.replace("_", " ")}</button>)}</div></section>
    <div className="ops-metric-grid policy-metrics"><article><span>Active rules</span><strong>{stats.active}</strong><small>Enforced in profile</small></article><article className="is-critical"><span>Blacklisted binaries</span><strong>{stats.blacklisted}</strong><small>Hard policy blocks</small></article><article className="is-warning"><span>High-risk patterns</span><strong>{stats.highRisk}</strong><small>AST match expressions</small></article><article className="is-blue"><span>Intercepted actions</span><strong>{stats.intercepted}</strong><small>Current audit window</small></article></div>
    <SignalDock eyebrow="Gate signal" title="Syntax is held at the threshold." detail="The active profile is watching each command shape before it reaches a protected runtime." values={[{ label: "Gate mode", value: mode.replace("_", " ") }, { label: "Hard blocks", value: String(stats.blacklisted) }, { label: "Last intercept", value: "09:28" }]} />
    {notice && <p className="operation-notice"><ShieldCheck size={15} />{notice}</p>}
    <div className="governance-grid"><section className="ops-panel glass-surface policy-matrix"><header className="ops-panel-title"><div><p className="eyebrow">Rule matrix</p><h2>Blocked commands & patterns</h2></div><SlidersHorizontal size={17} /></header><div className="rule-table-head"><span>Binary & flags</span><span>Category</span><span>Severity</span><span>State</span></div><div className="rule-list">{rules.map((rule) => <article className={`rule-row ${expandedRuleId === rule.id ? "is-expanded" : ""}`} key={rule.id}><button className="rule-row-main" type="button" onClick={() => onExpandRule(expandedRuleId === rule.id ? null : rule.id)}><span><strong>{rule.binaryName}</strong><small>{rule.forbiddenFlags.join(" · ")}</small></span><em>{categoryLabels[rule.category]}</em><b className={`rule-severity rule-severity--${rule.severity.toLowerCase()}`}>{rule.severity.replace("_", " ")}</b><ChevronDown size={15} /></button><div className="rule-row-toggle"><button className={rule.enabled ? "is-enabled" : ""} type="button" role="switch" aria-checked={rule.enabled} onClick={() => onToggleRule(rule.id)}><i /></button></div>{expandedRuleId === rule.id && <div className="rule-inspector"><div><span>Exact match</span><code>{rule.matchExpression}</code></div><div><span>Rationale</span><p>{rule.reasonDescription}</p></div></div>}</article>)}</div></section>
      <section className="ops-panel glass-surface ast-canvas"><header className="ops-panel-title"><div><p className="eyebrow">Syntax canvas</p><h2>AST risk visualizer</h2></div><Braces size={17} /></header><form onSubmit={(event) => { event.preventDefault(); onAnalyze(new FormData(event.currentTarget).get("command")?.toString() || astSimulation.command); }} className="ast-command-form"><Code2 size={15} /><input name="command" defaultValue={astSimulation.command} aria-label="CLI syntax to analyze" /><button type="submit">Analyze</button></form><div className="ast-tree">{astSimulation.nodes.map((node, index) => <div className={`ast-node ast-node--${node.risk}`} key={node.id}><span>{index + 1}</span><div><small>{node.label}</small><strong>{node.kind}</strong></div></div>)}</div><div className="risk-meter"><div><span>Syntax risk</span><strong>{astSimulation.riskScore}%</strong></div><i><em style={{ width: `${astSimulation.riskScore}%` }} /></i><p><AlertTriangle size={14} />Tripped node: <b>{astSimulation.trippedNode}</b></p></div></section></div>
    <Dialog open={editorOpen} onOpenChange={onOpenEditor}><DialogContent className="luma-management-dialog ops-rule-editor" showCloseButton={false}><div className="ops-drawer-shell"><header className="ops-drawer-header"><div><p className="eyebrow">Policy authoring</p><DialogTitle>Define custom rule</DialogTitle><DialogDescription>This form is presentation-only until a policy adapter is connected.</DialogDescription></div><DialogClose className="management-dialog-close" aria-label="Close rule editor">×</DialogClose></header><form className="rule-editor-form" onSubmit={(event) => { event.preventDefault(); onSaveRule(); }}><label>Binary name<input required placeholder="e.g. systemctl" /></label><label>Forbidden flags<input required placeholder="e.g. stop, disable" /></label><label>Severity level<select defaultValue="REQUIRE_APPROVAL"><option>CRITICAL_BLOCK</option><option>REQUIRE_APPROVAL</option></select></label><label className="is-wide">Reason description<textarea required placeholder="Explain why this action needs a block or human approval." /></label><button className="ops-primary-button" type="submit">Validate rule draft</button></form></div></DialogContent></Dialog>
  </section>;
}
