import { Download, Filter, GitBranch, ScanLine } from "lucide-react";
import type { TimelineEngineData, TimelineEvent, WorkspaceViewProps } from "@/types/workspace-cards";

type TimelineEngineCardProps = WorkspaceViewProps<TimelineEngineData> & { commandsOnly: boolean; failuresOnly: boolean; expandedEventId: string | null; onCommandsOnlyChange: (value: boolean) => void; onFailuresOnlyChange: (value: boolean) => void; onExpandEvent: (id: string | null) => void; };
const compactTime = (timestamp: string) => new Date(timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" });
function Snapshot({ event }: { event: TimelineEvent }) { return event.beforeMetrics && event.afterMetrics ? <div className="timeline-snapshot"><span>Before · CPU {event.beforeMetrics.cpu}% / RAM {event.beforeMetrics.ram}%</span><span>After · CPU {event.afterMetrics.cpu}% / RAM {event.afterMetrics.ram}%</span></div> : null; }

export function TimelineEngineCard({ context, data, onAction, className = "", commandsOnly, failuresOnly, expandedEventId, onCommandsOnlyChange, onFailuresOnlyChange, onExpandEvent }: TimelineEngineCardProps) {
  const events = data.events.filter((event) => (!commandsOnly || event.type === "CLI_EXECUTION") && (!failuresOnly || event.isCritical));
  return <section className={`workspace-card timeline-card ${className}`.trim()} aria-label="Incident post-mortem timeline"><header className="workspace-card-head"><div><p className="eyebrow">{context.activeIncidentId} · chronological trace</p><h2>Timeline engine</h2><span>Diagnostic events, decisions, and approvals held on one measured path.</span></div><button className="workspace-quiet-action" type="button" onClick={() => onAction?.("EXPORT_RCA", { incidentId: context.activeIncidentId })}><Download size={13} />Export RCA</button></header><div className="timeline-toolbar"><span><Filter size={12} />Trace filter</span><label><input type="checkbox" checked={commandsOnly} onChange={(event) => onCommandsOnlyChange(event.target.checked)} />Commands</label><label><input type="checkbox" checked={failuresOnly} onChange={(event) => onFailuresOnlyChange(event.target.checked)} />Critical</label></div><div className="timeline-stream">{events.map((event) => <article key={event.id} className={`timeline-event timeline-event--${event.type.toLowerCase()} ${event.isCritical ? "is-critical" : ""} ${expandedEventId === event.id ? "is-expanded" : ""}`}><button type="button" onClick={() => onExpandEvent(expandedEventId === event.id ? null : event.id)}><time>{compactTime(event.timestamp)}</time><span className="timeline-type"><GitBranch size={13} />{event.type.replace("_", " ")}</span><div><strong>{event.title}</strong><p>{event.description}</p><Snapshot event={event} /></div><ScanLine size={14} /></button></article>)}</div></section>;
}
