import { Activity, Network, ServerCog, X } from "lucide-react";
import type { TopologyMapData, WorkspaceViewProps } from "@/types/workspace-cards";

type TopologyMapCardProps = WorkspaceViewProps<TopologyMapData> & { selectedNodeId: string | null; onSelectNode: (id: string | null) => void; };
const positions: Record<string, { x: number; y: number }> = { nginx: { x: 106, y: 98 }, api: { x: 290, y: 164 }, postgres: { x: 474, y: 93 }, worker: { x: 450, y: 258 } };

export function TopologyMapCard({ context, data, selectedNodeId, onSelectNode, className = "" }: TopologyMapCardProps) {
  const selected = data.nodes.find((node) => node.id === selectedNodeId) ?? null;
  return <section className={`workspace-card topology-card ${className}`.trim()} aria-label="Live network and service topology map">
    <header className="workspace-card-head"><div><p className="eyebrow">{context.targetHostname} · service mesh</p><h2>Topology map</h2><span>Bound paths remain observable across the active incident surface.</span></div><span className="workspace-card-state"><Activity size={13} />LIVE</span></header>
    <div className="topology-canvas"><svg viewBox="0 0 580 330" role="img" aria-label="Service dependency graph"><defs><filter id="topologyGlow"><feGaussianBlur stdDeviation="3" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>{data.edges.map((edge) => { const source = positions[edge.sourceNodeId]; const target = positions[edge.targetNodeId]; return <g key={edge.id} className={edge.hasErrors ? "topology-edge is-error" : "topology-edge"}><line x1={source.x} y1={source.y} x2={target.x} y2={target.y} /><circle r="4"><animateMotion dur={edge.hasErrors ? "1.1s" : "2.2s"} repeatCount="indefinite" path={`M ${source.x} ${source.y} L ${target.x} ${target.y}`} /></circle><text x={(source.x + target.x) / 2} y={(source.y + target.y) / 2 - 8}>{edge.latencyMs}ms</text></g>; })}{data.nodes.map((node) => { const point = positions[node.id]; return <g key={node.id} className={`topology-node topology-node--${node.status.toLowerCase()} ${selectedNodeId === node.id ? "is-selected" : ""}`} role="button" tabIndex={0} onClick={() => onSelectNode(node.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") onSelectNode(node.id); }}><circle cx={point.x} cy={point.y} r="33" filter="url(#topologyGlow)" /><circle cx={point.x} cy={point.y} r="26" /><text x={point.x} y={point.y - 2}>{node.label}</text><text className="topology-node-type" x={point.x} y={point.y + 12}>{node.type.replace("_", " ")}</text></g>; })}</svg><div className="topology-legend"><span><i className="is-healthy" />Stable</span><span><i className="is-degraded" />Variance</span><span><i className="is-critical" />Error path</span></div></div>
    {selected && <aside className="topology-inspector" aria-label={`${selected.label} inspector`}><button type="button" aria-label="Close node inspector" onClick={() => onSelectNode(null)}><X size={15} /></button><span className={`topology-inspector-icon topology-node--${selected.status.toLowerCase()}`}><ServerCog size={17} /></span><div><p className="eyebrow">{selected.type.replace("_", " ")} · {selected.status}</p><strong>{selected.label}</strong></div><dl><div><dt>PID</dt><dd>{selected.pid}</dd></div><div><dt>Memory</dt><dd>{selected.memoryMb} MB</dd></div><div><dt>Open FDs</dt><dd>{selected.openFds}</dd></div></dl><div className="topology-ports">{selected.ports.map((port) => <code key={port}>{port}</code>)}</div></aside>}
  </section>;
}
