global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1h
  receiver: 'lupin-control-plane'

receivers:
- name: 'lupin-control-plane'
  webhook_configs:
  - url: 'http://host.docker.internal:3001/alerts'
    send_resolved: true
    max_alerts: 10
